### ISSUE TITLE
qs_ks_build_kohn_sham_matrix references undefined variable virial%pv_xc

### ISSUE THREAD

**Issue by vzecca** [cp2k/cp2k#1293]
Running test case QS/regtest-kp-2/Ar_1.inp in file qs_ks_methods.F line 632

virial%pv_exc = virial%pv_exc - virial%pv_xc

the undefined variable virial%pv_xc is referenced.

**Comment by dev-zero** [comment]
do you maybe meant "uninitialized" ?

**Comment by vzecca** [comment]
In Fortran variables are defined or undefined.
In this case, undefined because uninitialized.

**Comment by oschuett** [comment]
Fixed via #1309.

**Comment by vzecca** [comment]
I still get access to undefined variable virial%pv_xc.

In my opinion the origin of the bug is in xc.F lines 122 and 1064

     REAL(KIND=dp), DIMENSION(3, 3), INTENT(OUT)      :: virial_xc

where the  INTENT should be INOUT.
I remind you that INTENT(OUT) undefines the formal argument and the associated actual argument.

**Comment by oschuett** [comment]
@vzecca thanks for double checking. You seem to have a very good understanding of this problem. Maybe you could just prepare a pull request?

**Comment by vzecca** [comment]
It's not me, but I am using an excellent tool as the NAG nagfor compiler.
I do not know git enough to use it in a professional way, so I better leave it to people
that knows it better.
What I can say is that cp2k makes a liberal use of INTENT(OUT) also because
gfortran does not undefine the actual argument. The day gfortran will strictly obey the Fortran standard cp2k will probably break here and there.
Better to prevent than to cure.

**Comment by oschuett** [comment]
Fixed via #1333.
