### ISSUE TITLE
Overflow for large values of natoms in qs_overlap.F, possibly other related bugs.

### ISSUE THREAD

**Issue by LStuber** [cp2k/cp2k#811]
The test case H2O-dft-ls.inp seems to either hang or seg fault for NREP >= 8, at least partially due to this overflow:

https://github.com/cp2k/cp2k/blob/8bd161b65d4595e660da4bb714d97cfe7163ab74/src/qs_overlap.F#L342

In my run the hash becomes negative, which is clearly unexpected and leads to thread deadlocks. However even after fixing this line, other segfaults appear, so I suspect it is not the only issue.

**Build configuration:**
- master branch `40eef542,` arch "local_cuda", but I expect it to also happen in the CPU version.
- reverting to v7.1.0 fixes all issues.

**Comment by oschuett** [comment]
The most likely culprit is the OpenMP refactoring in https://github.com/cp2k/cp2k/commit/63f2e15396cd4d5323c594035dca6ba31437099f. 

However, I made a follow up [commit](https://github.com/cp2k/cp2k/commit/597fd47498f20c64e174034c8826a69f9b7252d7) where I moved `force_thread(3, natom)` from heap to stack in order to satisfy ` OMP REDUCTION`.

**Comment by oschuett** [comment]
I'm wondering if we could somehow add a test for this. Maybe a box with 1M ghost atoms?

**Comment by oschuett** [comment]
Should have be fixed via #812. @LStuber, can you confirm?

**Comment by LStuber** [comment]
I gave it a new try with the master branch 08691cf2 which includes the commit you're referring to, and the issue did not seem fixed (It still hangs for NREP=8). I will try to investigate it further tomorrow.

Hang stack trace:
```
#5  0x00007f1db09895b5 in gomp_set_lock__25 (lock=<optimized out>) at ../../../libgomp/fortran.c:216
#6  0x0000000000dd3795 in qs_overlap::__qs_overlap_MOD_build_overlap_matrix_low._omp_fn.3 () at src/qs_overlap.F:478
#7  0x00007f1db097df0f in GOMP_parallel (fn=0xdd1270 <qs_overlap::__qs_overlap_MOD_build_overlap_matrix_low._omp_fn.3>, data=0x7ffcc678b6a0, num_threads=5, flags=0) at ../../../libgomp/parallel.c:168
#8  0x0000000000dd6d30 in __qs_overlap_MOD_build_overlap_matrix_low () at src/qs_overlap.F:311
#9  0x0000000000dd8e0b in qs_overlap::build_overlap_matrix (ks_env=0xd597e60, matrix_s=<error reading variable: Location address is not set.>, matrixkp_s=..., matrix_name=<error reading variable: value requires 855585200 bytes, which is more than max-value-size>, nderivative=0, basis_type_a=<error reading variable: value requires 855585376 bytes, which is more than max-value-size>, basis_type_b=<error reading variable: value requires 855585552 bytes, which is more than max-value-size>, sab_nl=..., calculate_forces=<error reading variable: Cannot access memory at address 0x0>, matrix_p=<error reading variable: Cannot access memory at address 0x0>, matrixkp_p=<error reading variable: Location address is not set.>, _matrix_name=14, _basis_type_a=3, _basis_type_b=3) at src/qs_overlap.F:142
#10 0x000000000113a378 in qs_core_hamiltonian::build_core_hamiltonian_matrix (qs_env=0xd246530, calculate_forces=.FALSE.) at src/qs_core_hamiltonian.F:308
#11 0x000000000084377e in qs_energy_init::qs_energies_init_hamiltonians (molecule_only=3329803468, calc_forces=3329804808, qs_env=0xd249780) at src/qs_energy_init.F:318
```

**Comment by vondele** [comment]
will need the followup https://github.com/cp2k/cp2k/pull/813

**Comment by LStuber** [comment]
I confirm the issue is fixed now on the current master branch (that includes #812 and #813 fixes).
